name: wallpaper
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  get: any
  open_file: ^3.2.1
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.1.1
  flutter_wallpaper_manager: ^0.0.4
  flutter_cache_manager: ^3.3.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
